CREATE TABLE [dbo].[Review]
(
	[Id] INT NOT NULL IDENTITY(1,1),
    [Name]  NVARCHAR (50) NOT NULL,
    [DateOfBirth]   DATE NOT NULL,
    [Message] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Review] PRIMARY KEY CLUSTERED ([Id] ASC)
)
