using System.Web;
using System.Web.Optimization;

namespace BS.UI
{
    public class BundleConfig
    {
        // Дополнительные сведения об объединении см. на странице https://go.microsoft.com/fwlink/?LinkId=301862
        public static void RegisterBundles(BundleCollection bundles)
        {
            bundles.Add(new ScriptBundle("~/bundles/jquery").Include(
                        "~/Scripts/jquery-{version}.js"));

            bundles.Add(new ScriptBundle("~/bundles/jqueryval").Include(
                        "~/Scripts/jquery.validate*"));

            // Используйте версию Modernizr для разработчиков, чтобы учиться работать. Когда вы будете готовы перейти к работе,
            // готово к выпуску, используйте средство сборки по адресу https://modernizr.com, чтобы выбрать только необходимые тесты.
            bundles.Add(new ScriptBundle("~/bundles/modernizr").Include(
                        "~/Scripts/modernizr-*"));

            bundles.Add(new ScriptBundle("~/bundles/knockout").Include(
                         "~/Scripts/knockout-3.4.2.js",
                         "~/Scripts/knockout.mapping-latest.js"));

            bundles.Add(new ScriptBundle("~/bundles/bootstrap").Include(
                      "~/Scripts/bootstrap.js",
                      "~/Scripts/respond.js",
                      "~/Scripts/select2.min.js"));

            bundles.Add(new ScriptBundle("~/bundles/actions").Include(
                      "~/Scripts/Actions.js",
                       "~/Scripts/BookManagement.js",
                       "~/Scripts/AuthorManagement.js",
                       "~/Scripts/KOCustomBindings.js",
                       "~/Scripts/Autogenerated/*.js",
                       "~/Scripts/Autogenerated/Book/*.js",
                       "~/Scripts/Autogenerated/Author/*.js"
                     ));

            bundles.Add(new StyleBundle("~/Content/css").Include(
                      "~/Content/bootstrap.css",
                      "~/Content/css/Styles.css",
                      "~/Content/css/select2.css"));
        }
    }
}
